plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - lib/jeckle/api.rb
    - lib/jeckle/request.rb
    - lib/jeckle/client.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/jeckle/api.rb

Metrics/PerceivedComplexity:
  Exclude:
    - lib/jeckle/api.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - "*.gemspec"

Metrics/ParameterLists:
  Exclude:
    - lib/jeckle/collection.rb

Metrics/MethodLength:
  Exclude:
    - lib/jeckle/api.rb
    - lib/jeckle/request.rb
    - lib/jeckle/attribute_aliasing.rb
    - lib/jeckle/middleware/raise_error.rb

Naming/PredicateMethod:
  AllowedMethods:
    - destroy

Gemspec/DevelopmentDependencies:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/**/*

Style/EmptyClassDefinition:
  Exclude:
    - spec/**/*

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/lib/jeckle/auth/oauth2_spec.rb

RSpec/DescribeClass:
  Exclude:
    - spec/lib/jeckle/errors_spec.rb
